{
 "title": "Bookings",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Subscription gap size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(eventuous_subscription_gap_count_events{job=\"bookings\"}) by (subscription_id)",
     "legendFormat": "{{subscription_id}}"
    }
   ]
  },
  {
   "title": "Subscription gap time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(eventuous_subscription_gap_seconds_s{job=\"bookings\"}) by (subscription_id)",
     "legendFormat": "{{subscription_id}}"
    }
   ]
  },
  {
   "title": "Eventstore operation 95p duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(eventstore_s_bucket{job=\"bookings\"}[$__rate_interval])) by (le, operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "HTTP requests rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_ms_count{job=\"bookings\"}[$__rate_interval])) by (http_method, http_status_code)",
     "legendFormat": "{{http_method}}: {{http_status_code}}"
    }
   ]
  },
  {
   "title": "HTTP duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_ms_bucket{job=\"bookings\"}[$__rate_interval])) by (le, operation))",
     "legendFormat": "95p"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_duration_ms_bucket{job=\"bookings\"}[$__rate_interval])) by (le, operation))",
     "legendFormat": "50p"
    }
   ]
  }
 ]
}